name: Test for dev

on:
  push:
    branches:
      - dev

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master
        with:
          ref: dev
      - name: Install dependencies
        run: npm install
      - name: Run test
        run: npm run test
