name: Deploy process

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Install dependencies
        run: npm install
      - name: Run test
        run: npm run test
  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Archive build artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: ./dist
  deploy:
    name: Deploy
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Download artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: ./dist
      - name: deploy
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '274.0.1'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          service_account_email: ${{ secrets.GCP_SA_ACCOUNT }}
      - run: |
          echo ${{ secrets.GCP_SA_KEY }} | base64 --decode > "$HOME"/gcloud.json
          sh -c "gcloud auth activate-service-account --key-file=$HOME/gcloud.json $*"
          gcloud functions deploy sendDailyReport --project rescuetime --source ./dist --service-account ${{ secrets.GCP_SA_ACCOUNT }}
      # - name: Install gcloud SDK
      #   run: |
      #     sudo apt-get update && sudo apt-get install google-cloud-sdk
      # - name: Activate Service Account
      #   env:
      #     GCP_AUTH: ${{ secrets.GCP_SA_KEY }}
      #   run: |
      #     echo "$GCP_AUTH" | base64 --decode > "$HOME"/gcloud.json
      #     sh -c "gcloud auth activate-service-account --key-file=$HOME/gcloud.json $*"
      # - name: Deploy
      #   run: npm run deploy:daily
